version: "3.8"
services:
  app:
    build: ./docker/app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "yarn dev" # コンテナビルドが終わったら一旦コンテナ停止をして、コメントアウトを外す
    depends_on:
      - server
  server:
    build: ./docker/server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
    tty: true
    command: sh -c "yarn start:dev" # コンテナビルドが終わったら一旦コンテナ停止をして、コメントアウトを外す
